(function(module){
    module.util={
        apiPath:"https://mobile.mmears.com/preview/api/",
        dataCache:{
            bgMusic:"https://mobile.mmears.com/mmears-preview-source/dist/static/wav/background.mp3",//背景音乐地址
            lesson:{},//当前课程数据
            pages:{},//页数据
            pageIndex:0,
            scores:[],//积分数据
        }
    };
})(this.global?global:window)